CREATE TABLE client (
    id BINARY(16) NOT NULL PRIMARY KEY,
    secret VARCHAR(255) NOT NULL,
    redirect_uri VARCHAR(2048) NOT NULL,
    scopes VARCHAR(1024) NOT NULL,
    authorized_grant_types VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
